// Callvia Free Trial Agreement, version 1.
//
// The clause text is transcribed verbatim from the Google Form this replaces.
// Three mechanical changes, and nothing else:
//
//   1. "the Murphy Farm Services LLC" -> "{{businessName}}". The stray "the"
//      went with it; it only read correctly because a specific client's name
//      had been typed in.
//   2. "(7/23/26 - 8/6/26)" -> "({{trialStartDate}} - {{trialEndDate}})",
//      which render as "July 23, 2026 - August 6, 2026".
//   3. The Privacy Policy and Terms hyperlinks became spelled-out URLs. This
//      document gets printed to PDF, where a link with no visible address is
//      a dead end.
//
// NOTE: the original skips section 4. It goes 3, 5, 6, 7, 8. That gap is
// reproduced here rather than silently renumbered, because changing the
// numbering of an executed contract is a substantive edit, not a typo fix.
// Renumbering is a one-line change if you want it.
//
// FROZEN once the first client signs against it. Do not edit this file after
// that point: change means a new trial-v2.ts and a new row in
// agreement_templates. The freeze guard in registry.ts is what stops an
// accidental edit from silently changing what new clients are shown.
//
// NOT LEGAL ADVICE, and this text has not been reviewed by an attorney. A free
// trial that converts to a paid subscription is the exact shape
// automatic-renewal statutes care about. Keeping Stripe out of the trial is
// what keeps that exposure small: nothing in this document can start a charge.

import type { AgreementTemplate } from "../types";

export const trialV1: AgreementTemplate = {
  templateId: "callvia-free-trial",
  version: 1,
  title: "Callvia Free Trial Agreement",
  lastUpdated: "August 1, 2026",
  sections: [
    {
      blocks: [
        {
          kind: "p",
          text:
            'This Free Trial Agreement ("Agreement") is entered into between Callvia ("Callvia," "we," "us") and the participating business ("Client," "you").',
        },
      ],
    },
    {
      heading: "1. Free Trial",
      blocks: [
        {
          kind: "p",
          text:
            "Callvia agrees to provide its AI receptionist services to {{businessName}} at no charge during the agreed-upon trial period ({{trialStartDate}} - {{trialEndDate}}). Unless otherwise agreed in writing, either party may end the trial at any time.",
        },
      ],
    },
    {
      heading: "2. Purpose of the Trial",
      blocks: [
        {
          kind: "p",
          text:
            "The purpose of the trial is to allow the Client to evaluate Callvia's AI receptionist services before deciding whether to purchase a subscription.",
        },
      ],
    },
    {
      heading: "3. Client Responsibilities",
      blocks: [
        {
          kind: "p",
          text:
            "The Client understands that the services are provided on a trial basis. While Callvia strives to provide reliable service, uninterrupted operation, perfect call handling, or error-free performance cannot be guaranteed.",
        },
      ],
    },
    {
      heading: "5. Limitation of Liability",
      blocks: [
        {
          kind: "p",
          text:
            "To the fullest extent permitted by law, Callvia shall not be liable for any lost revenue, missed leads, business interruption, indirect damages, consequential damages, or other losses arising from or related to the free trial.",
        },
      ],
    },
    {
      heading: "6. No Obligation",
      blocks: [
        {
          kind: "p",
          text:
            "The Client is under no obligation to purchase a subscription after the trial ends. Likewise, Callvia may decline to continue providing services after the trial.",
        },
      ],
    },
    {
      heading: "7. Governing Documents",
      blocks: [
        {
          kind: "p",
          text:
            "By signing this Agreement, the Client acknowledges that they have read and agree to Callvia's Privacy Policy (callvia.io/privacy) and Terms (callvia.io/terms).",
        },
        {
          kind: "p",
          text:
            "These documents are incorporated into this Agreement by reference and remain applicable during the trial except that no subscription fees are due unless the Client separately agrees to become a paying customer",
        },
      ],
    },
    {
      heading: "8. Acceptance",
      blocks: [
        {
          kind: "p",
          text:
            "By signing below, the Client agrees to the terms of this Free Trial Agreement.",
        },
      ],
    },
  ],
};
