// Callvia Service Agreement, version 1.
//
// FROZEN once the first client signs against it. Do not edit this file after
// that point: change means a new v2.ts and a new row in agreement_templates.
// Signed agreements render from their stored snapshot, but the freeze test in
// lib/agreement/registry.test-hash.ts is what stops an accidental edit from
// silently changing what new clients are shown.
//
// NOT LEGAL ADVICE. Sections 3, 10, and 11 are new relative to the previous
// static page and need attorney review before go-live. See the plan notes.

import type { AgreementTemplate } from "../types";

export const v1: AgreementTemplate = {
  templateId: "callvia-service-agreement",
  version: 1,
  title: "Callvia Service Agreement",
  lastUpdated: "July 21, 2026",
  sections: [
    {
      blocks: [
        {
          kind: "p",
          text:
            'This Service Agreement (the "Agreement") is entered into between Callvia ("Callvia," "we," "us," or "our") and {{businessName}} (the "Client," "you," or "your"), and governs Callvia\'s provision of AI receptionist services to you. The specific services, fees, and any usage rates applicable to you are set out in Schedule A below, which forms part of this Agreement.',
        },
      ],
    },
    {
      heading: "1. Services Provided",
      blocks: [
        {
          kind: "p",
          text: "Callvia provides AI-powered receptionist services on behalf of your business. The services included in your plan are listed in Schedule A. Depending on your configuration, these services may include:",
        },
        {
          kind: "ul",
          items: [
            "Answering inbound calls",
            "Collecting and confirming caller information",
            "Identifying the nature and urgency of each request",
            "Sending call summaries and follow-ups via SMS and/or email",
            "Optional call routing, transfers, or appointment booking, where enabled",
          ],
        },
        {
          kind: "p",
          text: "Callvia may add, improve, or modify features over time. We will not materially reduce the core services described in Schedule A without reasonable notice to you.",
        },
      ],
    },
    {
      heading: "2. Fees and Billing",
      blocks: [
        {
          kind: "p",
          text: "The fees payable under this Agreement are set out in Schedule A. In summary:",
        },
        {
          kind: "ul",
          items: [
            "You agree to pay the recurring subscription fee stated in Schedule A, billed monthly in advance.",
            "Any one-time setup fee stated in Schedule A is due at the time you sign this Agreement.",
            "Any usage beyond the allowance stated in Schedule A, where applicable, is billed at the overage rate stated there.",
            "Payments are processed securely through Stripe. By signing this Agreement and completing checkout, you authorize Callvia to charge your payment method on a recurring basis until you cancel.",
            "You are responsible for keeping a valid payment method on file and for any applicable taxes.",
          ],
        },
        {
          kind: "callout",
          text: "Failure to complete payment may result in suspension of services until the balance is resolved.",
        },
      ],
    },
    {
      heading: "3. Effective Date and Commencement of Services",
      blocks: [
        {
          kind: "p",
          text: "This Agreement is effective on the Signature Date shown below. Callvia's obligation to provide the Services begins upon Callvia's receipt of the first payment. If the first payment is not received within fourteen (14) days of the Signature Date, Callvia may terminate this Agreement on written notice, without liability to either party.",
        },
      ],
    },
    {
      heading: "4. Term and Cancellation",
      blocks: [
        {
          kind: "ul",
          items: [
            "This Agreement is month-to-month with no long-term commitment.",
            "You may cancel at any time, effective at the end of your current paid billing cycle, by emailing team@callvia.io or by using the billing portal link provided to you.",
            "Cancellation takes effect at the end of the current paid cycle. No refunds are provided for partial months after billing.",
            "Callvia may suspend or terminate services for non-payment, or for violation of this Agreement or our Terms and Conditions.",
          ],
        },
      ],
    },
    {
      heading: "5. Service Expectations",
      blocks: [
        {
          kind: "p",
          text: "Callvia aims to provide reliable, professional AI call handling. To deliver this, the Client is responsible for:",
        },
        {
          kind: "ul",
          items: [
            "Providing accurate and complete business information",
            "Keeping call-handling instructions, hours, and routing preferences up to date",
            "Ensuring any forwarding or phone configuration on your end is correctly set up",
            "Obtaining any consents required for recording or messaging your callers",
          ],
        },
        {
          kind: "p",
          text: "Callvia is not liable for missed opportunities or errors resulting from inaccurate, outdated, or incomplete information provided by the Client.",
        },
      ],
    },
    {
      heading: "6. Limitation of Liability",
      blocks: [
        {
          kind: "p",
          text: "Callvia services are provided on a commercially reasonable basis and are not a guaranteed substitute for a live human operator in every circumstance. To the maximum extent permitted by law, Callvia is not responsible for:",
        },
        {
          kind: "ul",
          items: [
            "Lost revenue or business arising from missed, delayed, or misinterpreted calls",
            "Technical outages, carrier failures, or interruptions beyond our reasonable control",
            "Indirect, incidental, special, or consequential damages of any kind",
          ],
        },
        {
          kind: "p",
          text: "In all cases, Callvia's total liability under this Agreement is limited to the amount you paid for services in the month in which the claim arose.",
        },
      ],
    },
    {
      heading: "7. Confidentiality",
      blocks: [
        {
          kind: "p",
          text: "Each party agrees to keep confidential any non-public business information it receives from the other in connection with this Agreement, and to use that information only to provide or receive the services. This obligation does not apply to information that is or becomes public through no fault of the receiving party, or that must be disclosed by law.",
        },
      ],
    },
    {
      heading: "8. Data and Privacy",
      blocks: [
        {
          kind: "p",
          text: "Callvia handles caller and business data in accordance with our Privacy Policy, available at callvia.io/privacy. You are responsible for ensuring your callers have provided any consent required for the collection, recording, and SMS follow-up described in that policy and in our Terms and Conditions.",
        },
        {
          kind: "p",
          text: "Callvia retains a record of this Agreement, including your electronic signature and the associated audit information described in Section 9, for as long as required to establish or defend legal claims.",
        },
      ],
    },
    {
      heading: "9. Electronic Signature and Records",
      blocks: [
        {
          kind: "p",
          text: "You consent to transact with Callvia electronically and to sign this Agreement using an electronic signature. Your typed name, submitted through the Callvia agreement page, constitutes your legally binding signature under the U.S. Electronic Signatures in Global and National Commerce Act (ESIGN) and applicable state law, and has the same effect as a handwritten signature.",
        },
        {
          kind: "p",
          text: "To view and retain this Agreement you need a device with internet access, a current web browser, an email account capable of receiving PDF attachments, and software able to open PDF files. A signed copy of this Agreement will be emailed to you immediately upon signature, and remains available to download from your agreement link.",
        },
        {
          kind: "p",
          text: "Callvia records the date and time of signature in UTC, the IP address and browser reported by the device used to sign, and a cryptographic hash of the exact document presented to you, and stores that information with this Agreement.",
        },
        {
          kind: "p",
          text: "You may withdraw your consent to transact electronically, or request a paper copy of this Agreement at no charge, by emailing team@callvia.io. Withdrawing consent does not affect the validity of any signature given before withdrawal, and may mean Callvia can no longer provide the services electronically.",
        },
      ],
    },
    {
      heading: "10. Authority and Acceptance",
      blocks: [
        {
          kind: "p",
          text: "By typing your name and submitting this Agreement, you represent that you are authorized to enter into this Agreement on behalf of {{businessName}}, and you acknowledge that you have read, understood, and agreed to the terms set out above, together with Schedule A, our Terms and Conditions, and our Privacy Policy.",
        },
        {
          kind: "p",
          text: "This Agreement, together with Schedule A, is the entire agreement between the parties regarding its subject matter. Callvia may propose changes to these terms in the future; any change applies only to a new agreement that you separately sign, and does not alter this signed Agreement.",
        },
      ],
    },
    {
      heading: "11. Contact",
      blocks: [
        {
          kind: "p",
          text: "Questions about this Agreement? Reach us at team@callvia.io or visit callvia.io.",
        },
      ],
    },
  ],
};
